name: publish

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Compile with latex-action
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          pre_compile: "tlmgr update --self"
      - name: Move PDF to Output Directory
        run: |
          mkdir -p output
          mv main.pdf output/
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

  # Deploy to GH Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
